default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: library_development
  username: library_user
  password: Library_user1
  host: localhost

test:
  <<: *default
  database: library_test
  username: library_user
  password: Library_user1
  host: localhost

production:
  <<: *default
  database: library_production
  username: library_user
  password: Library_user1
  host: localhost
